'use client';

import { useEffect, useState } from 'react';
import { Check, Copy, Plus, Save } from 'lucide-react';

interface Manager { id: string; name: string; slug: string; whatsappPhone: string; isActive: boolean; isDefault: boolean; _count?: { cartSubmissions: number; analyticsEvents: number } }
const blank = { name: '', slug: '', whatsappPhone: '', isActive: true, isDefault: false };

export default function ManagersPage() {
  const [items, setItems] = useState<Manager[]>([]); const [draft, setDraft] = useState(blank); const [editing, setEditing] = useState<string | null>(null); const [form, setForm] = useState(blank); const [error, setError] = useState(''); const [copied, setCopied] = useState('');
  const load = () => fetch('/api/admin/managers').then((response) => response.json()).then((data) => { if (Array.isArray(data)) setItems(data); });
  useEffect(() => { void load(); }, []);
  const save = async (payload: typeof blank, id?: string) => { setError(''); try { const response = await fetch(id ? `/api/admin/managers/${id}` : '/api/admin/managers', { method: id ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Ошибка сохранения'); setDraft(blank); setEditing(null); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Ошибка'); } };
  const copy = async (slug: string) => { const link = `${window.location.origin}/m/${slug}`; await navigator.clipboard.writeText(link); setCopied(slug); window.setTimeout(() => setCopied(''), 1500); };
  const fields = (value: typeof blank, update: (next: typeof blank) => void) => <div className="grid gap-3 md:grid-cols-[1fr_160px_220px_auto_auto] md:items-end"><label className="text-xs font-bold text-gray-600">Имя<input className="mt-1 w-full rounded-xl border px-3 py-2 text-sm" value={value.name} onChange={(event) => update({ ...value, name: event.target.value })} /></label><label className="text-xs font-bold text-gray-600">Slug ссылки<input className="mt-1 w-full rounded-xl border px-3 py-2 text-sm" value={value.slug} onChange={(event) => update({ ...value, slug: event.target.value.toLowerCase() })} placeholder="a" /></label><label className="text-xs font-bold text-gray-600">WhatsApp<input className="mt-1 w-full rounded-xl border px-3 py-2 text-sm" value={value.whatsappPhone} onChange={(event) => update({ ...value, whatsappPhone: event.target.value })} placeholder="7..." /></label><label className="flex h-10 items-center gap-2 text-sm font-bold"><input type="checkbox" checked={value.isActive} onChange={(event) => update({ ...value, isActive: event.target.checked })} />Активен</label><label className="flex h-10 items-center gap-2 text-sm font-bold"><input type="checkbox" checked={value.isDefault} onChange={(event) => update({ ...value, isDefault: event.target.checked })} />Основной</label></div>;
  return <div className="max-w-[1100px]"><div className="mb-6"><h2 className="text-xl font-bold">Менеджеры и WhatsApp-routing</h2><p className="mt-1 text-sm text-gray-500">Каждому менеджеру соответствует постоянная ссылка `/m/slug`. Номер хранится только на сервере и используется при создании заявки.</p></div>
    <div className="rounded-2xl border bg-white p-5 shadow-sm"><h3 className="mb-4 flex items-center gap-2 font-black"><Plus size={18} />Добавить менеджера</h3>{fields(draft, setDraft)}<button onClick={() => void save(draft)} className="mt-4 rounded-xl bg-accent px-5 py-2.5 text-sm font-bold text-white">Добавить</button></div>
    {error && <div className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}
    <div className="mt-5 space-y-3">{items.map((item) => <div key={item.id} className="rounded-2xl border bg-white p-5 shadow-sm">{editing === item.id ? <>{fields(form, setForm)}<div className="mt-4 flex gap-2"><button onClick={() => void save(form, item.id)} className="flex items-center gap-2 rounded-xl bg-accent px-4 py-2 text-sm font-bold text-white"><Save size={15} />Сохранить</button><button onClick={() => setEditing(null)} className="rounded-xl border px-4 py-2 text-sm font-bold">Отмена</button></div></> : <div className="flex flex-wrap items-center justify-between gap-4"><div><div className="flex items-center gap-2 font-black">{item.name}{item.isDefault && <span className="rounded-full bg-blue-50 px-2 py-1 text-[10px] text-blue-700">ОСНОВНОЙ</span>}{!item.isActive && <span className="rounded-full bg-gray-100 px-2 py-1 text-[10px] text-gray-500">ВЫКЛЮЧЕН</span>}</div><div className="mt-1 text-sm text-gray-500">/m/{item.slug} · {item.whatsappPhone} · заявок: {item._count?.cartSubmissions || 0}</div></div><div className="flex gap-2"><button onClick={() => void copy(item.slug)} className="flex items-center gap-2 rounded-xl border px-3 py-2 text-sm font-bold">{copied === item.slug ? <Check size={15} /> : <Copy size={15} />}{copied === item.slug ? 'Скопировано' : 'Ссылка'}</button><button onClick={() => { setEditing(item.id); setForm({ name: item.name, slug: item.slug, whatsappPhone: item.whatsappPhone, isActive: item.isActive, isDefault: item.isDefault }); }} className="rounded-xl border px-3 py-2 text-sm font-bold">Изменить</button></div></div>}</div>)}</div>
  </div>;
}
