'use client';

import { useEffect, useState } from 'react';
import { BarChart3, MessageCircle, PackagePlus, ShoppingCart } from 'lucide-react';

interface Report { summary: { views: number; adds: number; carts: number; whatsapp: number; submissions: number; amount: number; averageCheck: number; viewToCart: number; cartToWhatsapp: number }; topProducts: any[]; topCategories: any[]; managers: any[] }
const date = (value: Date) => value.toISOString().slice(0, 10);

export default function ReportsPage() {
  const [from, setFrom] = useState(date(new Date(Date.now() - 29 * 86_400_000))); const [to, setTo] = useState(date(new Date())); const [report, setReport] = useState<Report | null>(null); const [loading, setLoading] = useState(true);
  const load = () => { setLoading(true); fetch(`/api/admin/reports?from=${from}&to=${to}`).then((response) => response.json()).then(setReport).finally(() => setLoading(false)); };
  useEffect(() => { void load(); /* initial range */ }, []);
  const money = (value: number) => `${Math.round(value || 0).toLocaleString('ru-RU')} ₸`; const percent = (value: number) => `${((value || 0) * 100).toFixed(1)}%`;
  return <div className="max-w-[1200px]"><div className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-xl font-bold">Аналитика каталога</h2><p className="mt-1 text-sm text-gray-500">Тестовые события исключены. Суммы считаются по сохранённым WhatsApp-заявкам.</p></div><div className="flex flex-wrap items-end gap-2"><label className="text-xs font-bold">С<input type="date" value={from} onChange={(event) => setFrom(event.target.value)} className="mt-1 block rounded-xl border px-3 py-2 text-sm" /></label><label className="text-xs font-bold">По<input type="date" value={to} onChange={(event) => setTo(event.target.value)} className="mt-1 block rounded-xl border px-3 py-2 text-sm" /></label><button onClick={load} className="h-10 rounded-xl bg-accent px-4 text-sm font-bold text-white">Показать</button></div></div>
    {loading || !report ? <div className="py-20 text-center text-gray-400">Загрузка отчёта...</div> : <>
      <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[
        ['Просмотры товаров', report.summary.views, BarChart3, 'bg-blue-500'], ['Добавления', report.summary.adds, PackagePlus, 'bg-violet-500'], ['Открытия корзины', report.summary.carts, ShoppingCart, 'bg-amber-500'], ['WhatsApp-клики', report.summary.whatsapp, MessageCircle, 'bg-green-500'],
      ].map(([label, value, Icon, color]: any) => <div key={label} className="rounded-2xl border bg-white p-4 shadow-sm"><div className={`mb-3 flex h-9 w-9 items-center justify-center rounded-xl text-white ${color}`}><Icon size={18} /></div><div className="text-2xl font-black">{value}</div><div className="text-sm text-gray-500">{label}</div></div>)}</div>
      <div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-2xl border bg-white p-4"><div className="text-xl font-black">{report.summary.submissions}</div><div className="text-sm text-gray-500">Заявок за период</div></div><div className="rounded-2xl border bg-white p-4"><div className="text-xl font-black">{money(report.summary.amount)}</div><div className="text-sm text-gray-500">Сумма заявок</div></div><div className="rounded-2xl border bg-white p-4"><div className="text-xl font-black">{money(report.summary.averageCheck)}</div><div className="text-sm text-gray-500">Средний чек</div></div><div className="rounded-2xl border bg-white p-4"><div className="text-xl font-black">{percent(report.summary.viewToCart)} / {percent(report.summary.cartToWhatsapp)}</div><div className="text-sm text-gray-500">Просмотр → корзина / корзина → WhatsApp</div></div></div>

      <section className="mt-6 overflow-hidden rounded-2xl border bg-white"><h3 className="border-b p-4 font-black">Товары</h3><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-gray-50 text-left text-xs"><tr><th className="p-3">Товар</th><th className="p-3 text-right">Просмотры</th><th className="p-3 text-right">В корзину</th><th className="p-3 text-right">В заявках</th><th className="p-3 text-right">Сумма заявок</th></tr></thead><tbody>{report.topProducts.map((item) => <tr key={item.id} className="border-t"><td className="p-3 font-bold">{item.name}</td><td className="p-3 text-right">{item.views}</td><td className="p-3 text-right">{item.adds}</td><td className="p-3 text-right">{item.whatsapp}</td><td className="p-3 text-right font-bold">{money(item.submissionAmount)}</td></tr>)}</tbody></table></div></section>
      <div className="mt-6 grid gap-6 lg:grid-cols-2"><section className="overflow-hidden rounded-2xl border bg-white"><h3 className="border-b p-4 font-black">Категории</h3>{report.topCategories.map((item) => <div key={item.id} className="flex justify-between border-b px-4 py-3 text-sm"><span className="font-bold">{item.name}</span><span>{item.views} просмотров · {item.adds} добавлений</span></div>)}</section><section className="overflow-hidden rounded-2xl border bg-white"><h3 className="border-b p-4 font-black">Менеджеры</h3>{report.managers.map((item) => <div key={item.id} className="border-b p-4"><div className="flex justify-between gap-3"><span className="font-black">{item.name}</span><span className="font-black">{money(item.amount)}</span></div><div className="mt-1 text-xs text-gray-500">Открытия: {item.catalogOpened} · корзины: {item.carts} · WhatsApp: {item.whatsapp} · заявки: {item.submissions}</div>{item.products?.length > 0 && <div className="mt-2 text-xs text-gray-600">В заявках: {item.products.map((product: any) => `${product.name} (${product.packages} уп.)`).join(', ')}</div>}</div>)}</section></div>
    </>}
  </div>;
}
